name: Custom build

on:
  workflow_dispatch:
    inputs:
      infuraId:
        description: "Infura ID"
        required: false
      fortmaticKey:
        description: "Fortmatic Key"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.14.2"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        env:
          FS_INFURA_ID: ${{github.event.inputs.infuraId}}
          FS_FORMATIC_KEY: ${{github.event.inputs.fortmaticKey}}
        run: |
          yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: filestorage-ui
          path: dist/
          if-no-files-found: error
